/** Otomatik üretildi — scripts/import-manual-brand-logos.mjs */
export const MANUAL_BRAND_LOGOS: Record<string, string> = {
  "kingbetting": "/brand-logos/kingbetting.png",
  "medusabahis": "/brand-logos/medusabahis.png",
  "betverse": "/brand-logos/betverse.png",
  "casifix": "/brand-logos/casifix.png",
  "efesbet": "/brand-logos/efesbet.png",
  "casinowon": "/brand-logos/casinowon.png",
  "ganyanbet": "/brand-logos/ganyanbet.png",
  "livebahis": "/brand-logos/livebahis.png",
  "betcool": "/brand-logos/betcool.png",
  "suratbet": "/brand-logos/suratbet.png",
  "sohobet": "/brand-logos/sohobet.png",
  "sonbahis": "/brand-logos/sonbahis.png",
  "betovis": "/brand-logos/betovis.png",
  "rotabet": "/brand-logos/rotabet.png",
  "pinbahis": "/brand-logos/pinbahis.png",
  "betist": "/brand-logos/betist.png",
  "betpark": "/brand-logos/betpark.png",
  "restbet": "/brand-logos/restbet.png",
  "betebet": "/brand-logos/betebet.png",
  "betboo": "/brand-logos/betboo.png",
  "bahsegel": "/brand-logos/bahsegel.png",
  "casinometropol": "/brand-logos/casinometropol.png",
  "betsat": "/brand-logos/betsat.png",
  "betlivo": "/brand-logos/betlivo.png",
  "betkare": "/brand-logos/betkare.png",
  "eyfelcasino": "/brand-logos/eyfelcasino.png",
  "etrobet": "/brand-logos/etrobet.png",
  "casinoas": "/brand-logos/casinoas.png",
  "gallerbahis": "/brand-logos/gallerbahis.png",
  "gobahis": "/brand-logos/gobahis.png"
};
