/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as BrandIndexRouteImport } from './routes/brand/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as BrandSikayetlerRouteImport } from './routes/brand/sikayetler'
import { Route as BrandProfilRouteImport } from './routes/brand/profil'
import { Route as BrandMesajlarRouteImport } from './routes/brand/mesajlar'
import { Route as BrandLoginRouteImport } from './routes/brand/login'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiTrendingRouteImport } from './routes/api/trending'
import { Route as ApiStatsRouteImport } from './routes/api/stats'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiResolutionsRouteImport } from './routes/api/resolutions'
import { Route as ApiReportsRouteImport } from './routes/api/reports'
import { Route as ApiProfileRouteImport } from './routes/api/profile'
import { Route as ApiOtpVerifyRouteImport } from './routes/api/otp/verify'
import { Route as ApiOtpSendRouteImport } from './routes/api/otp/send'
import { Route as ApiNotificationsRouteImport } from './routes/api/notifications'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiHistoryRouteImport } from './routes/api/history'
import { Route as ApiFastestResolversRouteImport } from './routes/api/fastest-resolvers'
import { Route as ApiEscalationsRouteImport } from './routes/api/escalations'
import { Route as ApiConversationsRouteImport } from './routes/api/conversations'
import { Route as ApiComplaintsRouteImport } from './routes/api/complaints'
import { Route as ApiComplaintRepliesRouteImport } from './routes/api/complaint-replies'
import { Route as ApiCommentsRouteImport } from './routes/api/comments'
import { Route as ApiCategoriesRouteImport } from './routes/api/categories'
import { Route as ApiBrandsRouteImport } from './routes/api/brands'
import { Route as ApiBrandVerificationRouteImport } from './routes/api/brand-verification'
import { Route as ApiBrandResolutionsRouteImport } from './routes/api/brand-resolutions'
import { Route as ApiBrandRatingsRouteImport } from './routes/api/brand-ratings'
import { Route as ApiComplaintRatingRouteImport } from './routes/api/complaint-rating'
import { Route as ApiCronComplaintBotRouteImport } from './routes/api/cron/complaint-bot'
import { Route as ApiBlogRouteImport } from './routes/api/blog'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as AdminSikayetlerRouteImport } from './routes/admin/sikayetler'
import { Route as AdminBotRouteImport } from './routes/admin/bot'
import { Route as AdminPremiumRouteImport } from './routes/admin/premium'
import { Route as AdminModerasyonRouteImport } from './routes/admin/moderasyon'
import { Route as AdminMedyaRouteImport } from './routes/admin/medya'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminKullanicilarRouteImport } from './routes/admin/kullanicilar'
import { Route as AdminKategorilerRouteImport } from './routes/admin/kategoriler'
import { Route as AdminFirmalarRouteImport } from './routes/admin/firmalar'
import { Route as AdminEscalationsRouteImport } from './routes/admin/escalations'
import { Route as AdminDogrulamaRouteImport } from './routes/admin/dogrulama'
import { Route as AdminCmsRouteImport } from './routes/admin/cms'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAyarlarRouteImport } from './routes/admin/ayarlar'
import { Route as SiteTrendlerRouteImport } from './routes/_site/trendler'
import { Route as SiteTrend100RouteImport } from './routes/_site/trend-100'
import { Route as SiteSikayetlerRouteImport } from './routes/_site/sikayetler'
import { Route as SiteSikayetYazRouteImport } from './routes/_site/sikayet-yaz'
import { Route as SiteProfileRouteImport } from './routes/_site/profile'
import { Route as SiteMarkalarRouteImport } from './routes/_site/markalar'
import { Route as SiteAramaRouteImport } from './routes/_site/arama'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as SiteBlogIndexRouteImport } from './routes/_site/blog.index'
import { Route as ApiMeComplaintsRouteImport } from './routes/api/me.complaints'
import { Route as ApiFilesSplatRouteImport } from './routes/api/files/$'
import { Route as ApiEventsComplaintIdRouteImport } from './routes/api/events/$complaintId'
import { Route as ApiComplaintsIdRouteImport } from './routes/api/complaints/$id'
import { Route as ApiCommentsVoteRouteImport } from './routes/api/comments/vote'
import { Route as ApiCommentsPinRouteImport } from './routes/api/comments/pin'
import { Route as ApiBrandsSlugRouteImport } from './routes/api/brands/$slug'
import { Route as ApiBrandStatsRouteImport } from './routes/api/brand/stats'
import { Route as ApiBrandBotConfigRouteImport } from './routes/api/brand/bot-config'
import { Route as ApiBrandProfileRouteImport } from './routes/api/brand/profile'
import { Route as ApiBrandPremiumRouteImport } from './routes/api/brand/premium'
import { Route as ApiBrandMembershipsRouteImport } from './routes/api/brand/memberships'
import { Route as ApiBrandComplaintsRouteImport } from './routes/api/brand/complaints'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminVerificationRouteImport } from './routes/api/admin/verification'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminStatsRouteImport } from './routes/api/admin/stats'
import { Route as ApiAdminSanctionsRouteImport } from './routes/api/admin/sanctions'
import { Route as ApiAdminPremiumRouteImport } from './routes/api/admin/premium'
import { Route as ApiAdminModerationRouteImport } from './routes/api/admin/moderation'
import { Route as ApiAdminMediaRouteImport } from './routes/api/admin/media'
import { Route as ApiAdminEscalationsRouteImport } from './routes/api/admin/escalations'
import { Route as ApiAdminComplaintsRouteImport } from './routes/api/admin/complaints'
import { Route as ApiAdminBotConfigRouteImport } from './routes/api/admin/bot/config'
import { Route as ApiAdminBotStatsRouteImport } from './routes/api/admin/bot/stats'
import { Route as ApiAdminBotComplaintsRouteImport } from './routes/api/admin/bot/complaints'
import { Route as ApiAdminBotGenerateRouteImport } from './routes/api/admin/bot/generate'
import { Route as ApiAdminBotRunsRouteImport } from './routes/api/admin/bot/runs'
import { Route as ApiAdminCmsRouteImport } from './routes/api/admin/cms'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiAdminBrandsRouteImport } from './routes/api/admin/brands'
import { Route as ApiAdminBlogsRouteImport } from './routes/api/admin/blogs'
import { Route as AdminFirmaIdRouteImport } from './routes/admin/firma.$id'
import { Route as SiteSikayetIdRouteImport } from './routes/_site/sikayet.$id'
import { Route as SiteKategoriSlugRouteImport } from './routes/_site/kategori.$slug'
import { Route as SiteFirmaSlugRouteImport } from './routes/_site/firma.$slug'
import { Route as SiteBlogSlugRouteImport } from './routes/_site/blog.$slug'
import { Route as SitekurumsalYardimRouteImport } from './routes/_site/(kurumsal)/yardim'
import { Route as SitekurumsalSeffaflikRaporuRouteImport } from './routes/_site/(kurumsal)/seffaflik-raporu'
import { Route as SitekurumsalReklamCozumleriRouteImport } from './routes/_site/(kurumsal)/reklam-cozumleri'
import { Route as SitekurumsalKvkkRouteImport } from './routes/_site/(kurumsal)/kvkk'
import { Route as SitekurumsalKullanimKosullariRouteImport } from './routes/_site/(kurumsal)/kullanim-kosullari'
import { Route as SitekurumsalIletisimRouteImport } from './routes/_site/(kurumsal)/iletisim'
import { Route as SitekurumsalHakkimizdaRouteImport } from './routes/_site/(kurumsal)/hakkimizda'
import { Route as SitekurumsalGizlilikRouteImport } from './routes/_site/(kurumsal)/gizlilik'
import { Route as SitekurumsalErisimYokRouteImport } from './routes/_site/(kurumsal)/erisim-yok'
import { Route as ApiAdminBrandsIdRouteImport } from './routes/api/admin/brands/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIndexRoute = BrandIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const BrandSikayetlerRoute = BrandSikayetlerRouteImport.update({
  id: '/sikayetler',
  path: '/sikayetler',
  getParentRoute: () => BrandRoute,
} as any)
const BrandProfilRoute = BrandProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => BrandRoute,
} as any)
const BrandMesajlarRoute = BrandMesajlarRouteImport.update({
  id: '/mesajlar',
  path: '/mesajlar',
  getParentRoute: () => BrandRoute,
} as any)
const BrandLoginRoute = BrandLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => BrandRoute,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrendingRoute = ApiTrendingRouteImport.update({
  id: '/api/trending',
  path: '/api/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStatsRoute = ApiStatsRouteImport.update({
  id: '/api/stats',
  path: '/api/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResolutionsRoute = ApiResolutionsRouteImport.update({
  id: '/api/resolutions',
  path: '/api/resolutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportsRoute = ApiReportsRouteImport.update({
  id: '/api/reports',
  path: '/api/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProfileRoute = ApiProfileRouteImport.update({
  id: '/api/profile',
  path: '/api/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtpVerifyRoute = ApiOtpVerifyRouteImport.update({
  id: '/api/otp/verify',
  path: '/api/otp/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOtpSendRoute = ApiOtpSendRouteImport.update({
  id: '/api/otp/send',
  path: '/api/otp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsRoute = ApiNotificationsRouteImport.update({
  id: '/api/notifications',
  path: '/api/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHistoryRoute = ApiHistoryRouteImport.update({
  id: '/api/history',
  path: '/api/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFastestResolversRoute = ApiFastestResolversRouteImport.update({
  id: '/api/fastest-resolvers',
  path: '/api/fastest-resolvers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEscalationsRoute = ApiEscalationsRouteImport.update({
  id: '/api/escalations',
  path: '/api/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsRoute = ApiConversationsRouteImport.update({
  id: '/api/conversations',
  path: '/api/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsRoute = ApiComplaintsRouteImport.update({
  id: '/api/complaints',
  path: '/api/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintRepliesRoute = ApiComplaintRepliesRouteImport.update({
  id: '/api/complaint-replies',
  path: '/api/complaint-replies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCommentsRoute = ApiCommentsRouteImport.update({
  id: '/api/comments',
  path: '/api/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCategoriesRoute = ApiCategoriesRouteImport.update({
  id: '/api/categories',
  path: '/api/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandsRoute = ApiBrandsRouteImport.update({
  id: '/api/brands',
  path: '/api/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandVerificationRoute = ApiBrandVerificationRouteImport.update({
  id: '/api/brand-verification',
  path: '/api/brand-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandResolutionsRoute = ApiBrandResolutionsRouteImport.update({
  id: '/api/brand-resolutions',
  path: '/api/brand-resolutions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandRatingsRoute = ApiBrandRatingsRouteImport.update({
  id: '/api/brand-ratings',
  path: '/api/brand-ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintRatingRoute = ApiComplaintRatingRouteImport.update({
  id: '/api/complaint-rating',
  path: '/api/complaint-rating',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronComplaintBotRoute = ApiCronComplaintBotRouteImport.update({
  id: '/api/cron/complaint-bot',
  path: '/api/cron/complaint-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlogRoute = ApiBlogRouteImport.update({
  id: '/api/blog',
  path: '/api/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSikayetlerRoute = AdminSikayetlerRouteImport.update({
  id: '/sikayetler',
  path: '/sikayetler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBotRoute = AdminBotRouteImport.update({
  id: '/bot',
  path: '/bot',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPremiumRoute = AdminPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerasyonRoute = AdminModerasyonRouteImport.update({
  id: '/moderasyon',
  path: '/moderasyon',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMedyaRoute = AdminMedyaRouteImport.update({
  id: '/medya',
  path: '/medya',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKullanicilarRoute = AdminKullanicilarRouteImport.update({
  id: '/kullanicilar',
  path: '/kullanicilar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKategorilerRoute = AdminKategorilerRouteImport.update({
  id: '/kategoriler',
  path: '/kategoriler',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFirmalarRoute = AdminFirmalarRouteImport.update({
  id: '/firmalar',
  path: '/firmalar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscalationsRoute = AdminEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDogrulamaRoute = AdminDogrulamaRouteImport.update({
  id: '/dogrulama',
  path: '/dogrulama',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAyarlarRoute = AdminAyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTrendlerRoute = SiteTrendlerRouteImport.update({
  id: '/trendler',
  path: '/trendler',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTrend100Route = SiteTrend100RouteImport.update({
  id: '/trend-100',
  path: '/trend-100',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSikayetlerRoute = SiteSikayetlerRouteImport.update({
  id: '/sikayetler',
  path: '/sikayetler',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSikayetYazRoute = SiteSikayetYazRouteImport.update({
  id: '/sikayet-yaz',
  path: '/sikayet-yaz',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProfileRoute = SiteProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SiteRoute,
} as any)
const SiteMarkalarRoute = SiteMarkalarRouteImport.update({
  id: '/markalar',
  path: '/markalar',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAramaRoute = SiteAramaRouteImport.update({
  id: '/arama',
  path: '/arama',
  getParentRoute: () => SiteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteBlogIndexRoute = SiteBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => SiteRoute,
} as any)
const ApiMeComplaintsRoute = ApiMeComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => ApiMeRoute,
} as any)
const ApiFilesSplatRoute = ApiFilesSplatRouteImport.update({
  id: '/api/files/$',
  path: '/api/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsComplaintIdRoute = ApiEventsComplaintIdRouteImport.update({
  id: '/api/events/$complaintId',
  path: '/api/events/$complaintId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiComplaintsIdRoute = ApiComplaintsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiComplaintsRoute,
} as any)
const ApiCommentsVoteRoute = ApiCommentsVoteRouteImport.update({
  id: '/vote',
  path: '/vote',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiCommentsPinRoute = ApiCommentsPinRouteImport.update({
  id: '/pin',
  path: '/pin',
  getParentRoute: () => ApiCommentsRoute,
} as any)
const ApiBrandsSlugRoute = ApiBrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiBrandsRoute,
} as any)
const ApiBrandStatsRoute = ApiBrandStatsRouteImport.update({
  id: '/api/brand/stats',
  path: '/api/brand/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandBotConfigRoute = ApiBrandBotConfigRouteImport.update({
  id: '/api/brand/bot-config',
  path: '/api/brand/bot-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandProfileRoute = ApiBrandProfileRouteImport.update({
  id: '/api/brand/profile',
  path: '/api/brand/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandPremiumRoute = ApiBrandPremiumRouteImport.update({
  id: '/api/brand/premium',
  path: '/api/brand/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandMembershipsRoute = ApiBrandMembershipsRouteImport.update({
  id: '/api/brand/memberships',
  path: '/api/brand/memberships',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrandComplaintsRoute = ApiBrandComplaintsRouteImport.update({
  id: '/api/brand/complaints',
  path: '/api/brand/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminVerificationRoute = ApiAdminVerificationRouteImport.update({
  id: '/api/admin/verification',
  path: '/api/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStatsRoute = ApiAdminStatsRouteImport.update({
  id: '/api/admin/stats',
  path: '/api/admin/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSanctionsRoute = ApiAdminSanctionsRouteImport.update({
  id: '/api/admin/sanctions',
  path: '/api/admin/sanctions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPremiumRoute = ApiAdminPremiumRouteImport.update({
  id: '/api/admin/premium',
  path: '/api/admin/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminModerationRoute = ApiAdminModerationRouteImport.update({
  id: '/api/admin/moderation',
  path: '/api/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaRoute = ApiAdminMediaRouteImport.update({
  id: '/api/admin/media',
  path: '/api/admin/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminEscalationsRoute = ApiAdminEscalationsRouteImport.update({
  id: '/api/admin/escalations',
  path: '/api/admin/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminComplaintsRoute = ApiAdminComplaintsRouteImport.update({
  id: '/api/admin/complaints',
  path: '/api/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotConfigRoute = ApiAdminBotConfigRouteImport.update({
  id: '/api/admin/bot/config',
  path: '/api/admin/bot/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotStatsRoute = ApiAdminBotStatsRouteImport.update({
  id: '/api/admin/bot/stats',
  path: '/api/admin/bot/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotComplaintsRoute = ApiAdminBotComplaintsRouteImport.update({
  id: '/api/admin/bot/complaints',
  path: '/api/admin/bot/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotGenerateRoute = ApiAdminBotGenerateRouteImport.update({
  id: '/api/admin/bot/generate',
  path: '/api/admin/bot/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBotRunsRoute = ApiAdminBotRunsRouteImport.update({
  id: '/api/admin/bot/runs',
  path: '/api/admin/bot/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCmsRoute = ApiAdminCmsRouteImport.update({
  id: '/api/admin/cms',
  path: '/api/admin/cms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBrandsRoute = ApiAdminBrandsRouteImport.update({
  id: '/api/admin/brands',
  path: '/api/admin/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminBlogsRoute = ApiAdminBlogsRouteImport.update({
  id: '/api/admin/blogs',
  path: '/api/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFirmaIdRoute = AdminFirmaIdRouteImport.update({
  id: '/firma/$id',
  path: '/firma/$id',
  getParentRoute: () => AdminRoute,
} as any)
const SiteSikayetIdRoute = SiteSikayetIdRouteImport.update({
  id: '/sikayet/$id',
  path: '/sikayet/$id',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKategoriSlugRoute = SiteKategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFirmaSlugRoute = SiteFirmaSlugRouteImport.update({
  id: '/firma/$slug',
  path: '/firma/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogSlugRoute = SiteBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalYardimRoute = SitekurumsalYardimRouteImport.update({
  id: '/(kurumsal)/yardim',
  path: '/yardim',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalSeffaflikRaporuRoute =
  SitekurumsalSeffaflikRaporuRouteImport.update({
    id: '/(kurumsal)/seffaflik-raporu',
    path: '/seffaflik-raporu',
    getParentRoute: () => SiteRoute,
  } as any)
const SitekurumsalReklamCozumleriRoute =
  SitekurumsalReklamCozumleriRouteImport.update({
    id: '/(kurumsal)/reklam-cozumleri',
    path: '/reklam-cozumleri',
    getParentRoute: () => SiteRoute,
  } as any)
const SitekurumsalKvkkRoute = SitekurumsalKvkkRouteImport.update({
  id: '/(kurumsal)/kvkk',
  path: '/kvkk',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalKullanimKosullariRoute =
  SitekurumsalKullanimKosullariRouteImport.update({
    id: '/(kurumsal)/kullanim-kosullari',
    path: '/kullanim-kosullari',
    getParentRoute: () => SiteRoute,
  } as any)
const SitekurumsalIletisimRoute = SitekurumsalIletisimRouteImport.update({
  id: '/(kurumsal)/iletisim',
  path: '/iletisim',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalHakkimizdaRoute = SitekurumsalHakkimizdaRouteImport.update({
  id: '/(kurumsal)/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalGizlilikRoute = SitekurumsalGizlilikRouteImport.update({
  id: '/(kurumsal)/gizlilik',
  path: '/gizlilik',
  getParentRoute: () => SiteRoute,
} as any)
const SitekurumsalErisimYokRoute = SitekurumsalErisimYokRouteImport.update({
  id: '/(kurumsal)/erisim-yok',
  path: '/erisim-yok',
  getParentRoute: () => SiteRoute,
} as any)
const ApiAdminBrandsIdRoute = ApiAdminBrandsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminBrandsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/arama': typeof SiteAramaRoute
  '/markalar': typeof SiteMarkalarRoute
  '/profile': typeof SiteProfileRoute
  '/sikayet-yaz': typeof SiteSikayetYazRoute
  '/sikayetler': typeof SiteSikayetlerRoute
  '/trend-100': typeof SiteTrend100Route
  '/trendler': typeof SiteTrendlerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dogrulama': typeof AdminDogrulamaRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/firmalar': typeof AdminFirmalarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/moderasyon': typeof AdminModerasyonRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/sikayetler': typeof AdminSikayetlerRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/brand-ratings': typeof ApiBrandRatingsRoute
  '/api/complaint-rating': typeof ApiComplaintRatingRoute
  '/api/cron/complaint-bot': typeof ApiCronComplaintBotRoute
  '/api/brand-resolutions': typeof ApiBrandResolutionsRoute
  '/api/brand-verification': typeof ApiBrandVerificationRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/complaint-replies': typeof ApiComplaintRepliesRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/fastest-resolvers': typeof ApiFastestResolversRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resolutions': typeof ApiResolutionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/upload': typeof ApiUploadRoute
  '/brand/login': typeof BrandLoginRoute
  '/brand/mesajlar': typeof BrandMesajlarRoute
  '/brand/profil': typeof BrandProfilRoute
  '/brand/sikayetler': typeof BrandSikayetlerRoute
  '/admin/': typeof AdminIndexRoute
  '/brand/': typeof BrandIndexRoute
  '/erisim-yok': typeof SitekurumsalErisimYokRoute
  '/gizlilik': typeof SitekurumsalGizlilikRoute
  '/hakkimizda': typeof SitekurumsalHakkimizdaRoute
  '/iletisim': typeof SitekurumsalIletisimRoute
  '/kullanim-kosullari': typeof SitekurumsalKullanimKosullariRoute
  '/kvkk': typeof SitekurumsalKvkkRoute
  '/reklam-cozumleri': typeof SitekurumsalReklamCozumleriRoute
  '/seffaflik-raporu': typeof SitekurumsalSeffaflikRaporuRoute
  '/yardim': typeof SitekurumsalYardimRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/firma/$slug': typeof SiteFirmaSlugRoute
  '/kategori/$slug': typeof SiteKategoriSlugRoute
  '/sikayet/$id': typeof SiteSikayetIdRoute
  '/admin/firma/$id': typeof AdminFirmaIdRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/brands': typeof ApiAdminBrandsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/complaints': typeof ApiAdminComplaintsRoute
  '/api/admin/bot/config': typeof ApiAdminBotConfigRoute
  '/api/admin/bot/stats': typeof ApiAdminBotStatsRoute
  '/api/admin/bot/complaints': typeof ApiAdminBotComplaintsRoute
  '/api/admin/bot/generate': typeof ApiAdminBotGenerateRoute
  '/api/admin/bot/runs': typeof ApiAdminBotRunsRoute
  '/api/admin/escalations': typeof ApiAdminEscalationsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/moderation': typeof ApiAdminModerationRoute
  '/api/admin/premium': typeof ApiAdminPremiumRoute
  '/api/admin/sanctions': typeof ApiAdminSanctionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/verification': typeof ApiAdminVerificationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brand/complaints': typeof ApiBrandComplaintsRoute
  '/api/brand/memberships': typeof ApiBrandMembershipsRoute
  '/api/brand/premium': typeof ApiBrandPremiumRoute
  '/api/brand/profile': typeof ApiBrandProfileRoute
  '/api/brand/stats': typeof ApiBrandStatsRoute
  '/api/brand/bot-config': typeof ApiBrandBotConfigRoute
  '/api/brands/$slug': typeof ApiBrandsSlugRoute
  '/api/comments/pin': typeof ApiCommentsPinRoute
  '/api/comments/vote': typeof ApiCommentsVoteRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/events/$complaintId': typeof ApiEventsComplaintIdRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/me/complaints': typeof ApiMeComplaintsRoute
  '/blog/': typeof SiteBlogIndexRoute
  '/api/admin/brands/$id': typeof ApiAdminBrandsIdRoute
}
export interface FileRoutesByTo {
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/reset-password': typeof authResetPasswordRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/arama': typeof SiteAramaRoute
  '/markalar': typeof SiteMarkalarRoute
  '/profile': typeof SiteProfileRoute
  '/sikayet-yaz': typeof SiteSikayetYazRoute
  '/sikayetler': typeof SiteSikayetlerRoute
  '/trend-100': typeof SiteTrend100Route
  '/trendler': typeof SiteTrendlerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dogrulama': typeof AdminDogrulamaRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/firmalar': typeof AdminFirmalarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/moderasyon': typeof AdminModerasyonRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/sikayetler': typeof AdminSikayetlerRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/brand-ratings': typeof ApiBrandRatingsRoute
  '/api/complaint-rating': typeof ApiComplaintRatingRoute
  '/api/cron/complaint-bot': typeof ApiCronComplaintBotRoute
  '/api/brand-resolutions': typeof ApiBrandResolutionsRoute
  '/api/brand-verification': typeof ApiBrandVerificationRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/complaint-replies': typeof ApiComplaintRepliesRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/fastest-resolvers': typeof ApiFastestResolversRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resolutions': typeof ApiResolutionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/upload': typeof ApiUploadRoute
  '/brand/login': typeof BrandLoginRoute
  '/brand/mesajlar': typeof BrandMesajlarRoute
  '/brand/profil': typeof BrandProfilRoute
  '/brand/sikayetler': typeof BrandSikayetlerRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/brand': typeof BrandIndexRoute
  '/erisim-yok': typeof SitekurumsalErisimYokRoute
  '/gizlilik': typeof SitekurumsalGizlilikRoute
  '/hakkimizda': typeof SitekurumsalHakkimizdaRoute
  '/iletisim': typeof SitekurumsalIletisimRoute
  '/kullanim-kosullari': typeof SitekurumsalKullanimKosullariRoute
  '/kvkk': typeof SitekurumsalKvkkRoute
  '/reklam-cozumleri': typeof SitekurumsalReklamCozumleriRoute
  '/seffaflik-raporu': typeof SitekurumsalSeffaflikRaporuRoute
  '/yardim': typeof SitekurumsalYardimRoute
  '/blog/$slug': typeof SiteBlogSlugRoute
  '/firma/$slug': typeof SiteFirmaSlugRoute
  '/kategori/$slug': typeof SiteKategoriSlugRoute
  '/sikayet/$id': typeof SiteSikayetIdRoute
  '/admin/firma/$id': typeof AdminFirmaIdRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/brands': typeof ApiAdminBrandsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/complaints': typeof ApiAdminComplaintsRoute
  '/api/admin/bot/config': typeof ApiAdminBotConfigRoute
  '/api/admin/bot/stats': typeof ApiAdminBotStatsRoute
  '/api/admin/bot/complaints': typeof ApiAdminBotComplaintsRoute
  '/api/admin/bot/generate': typeof ApiAdminBotGenerateRoute
  '/api/admin/bot/runs': typeof ApiAdminBotRunsRoute
  '/api/admin/escalations': typeof ApiAdminEscalationsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/moderation': typeof ApiAdminModerationRoute
  '/api/admin/premium': typeof ApiAdminPremiumRoute
  '/api/admin/sanctions': typeof ApiAdminSanctionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/verification': typeof ApiAdminVerificationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brand/complaints': typeof ApiBrandComplaintsRoute
  '/api/brand/memberships': typeof ApiBrandMembershipsRoute
  '/api/brand/premium': typeof ApiBrandPremiumRoute
  '/api/brand/profile': typeof ApiBrandProfileRoute
  '/api/brand/stats': typeof ApiBrandStatsRoute
  '/api/brand/bot-config': typeof ApiBrandBotConfigRoute
  '/api/brands/$slug': typeof ApiBrandsSlugRoute
  '/api/comments/pin': typeof ApiCommentsPinRoute
  '/api/comments/vote': typeof ApiCommentsVoteRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/events/$complaintId': typeof ApiEventsComplaintIdRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/me/complaints': typeof ApiMeComplaintsRoute
  '/blog': typeof SiteBlogIndexRoute
  '/api/admin/brands/$id': typeof ApiAdminBrandsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/brand': typeof BrandRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/_site/arama': typeof SiteAramaRoute
  '/_site/markalar': typeof SiteMarkalarRoute
  '/_site/profile': typeof SiteProfileRoute
  '/_site/sikayet-yaz': typeof SiteSikayetYazRoute
  '/_site/sikayetler': typeof SiteSikayetlerRoute
  '/_site/trend-100': typeof SiteTrend100Route
  '/_site/trendler': typeof SiteTrendlerRoute
  '/admin/ayarlar': typeof AdminAyarlarRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cms': typeof AdminCmsRoute
  '/admin/dogrulama': typeof AdminDogrulamaRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/firmalar': typeof AdminFirmalarRoute
  '/admin/kategoriler': typeof AdminKategorilerRoute
  '/admin/kullanicilar': typeof AdminKullanicilarRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/medya': typeof AdminMedyaRoute
  '/admin/moderasyon': typeof AdminModerasyonRoute
  '/admin/premium': typeof AdminPremiumRoute
  '/admin/sikayetler': typeof AdminSikayetlerRoute
  '/admin/bot': typeof AdminBotRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/blog': typeof ApiBlogRoute
  '/api/brand-ratings': typeof ApiBrandRatingsRoute
  '/api/complaint-rating': typeof ApiComplaintRatingRoute
  '/api/cron/complaint-bot': typeof ApiCronComplaintBotRoute
  '/api/brand-resolutions': typeof ApiBrandResolutionsRoute
  '/api/brand-verification': typeof ApiBrandVerificationRoute
  '/api/brands': typeof ApiBrandsRouteWithChildren
  '/api/categories': typeof ApiCategoriesRoute
  '/api/comments': typeof ApiCommentsRouteWithChildren
  '/api/complaint-replies': typeof ApiComplaintRepliesRoute
  '/api/complaints': typeof ApiComplaintsRouteWithChildren
  '/api/conversations': typeof ApiConversationsRoute
  '/api/escalations': typeof ApiEscalationsRoute
  '/api/fastest-resolvers': typeof ApiFastestResolversRoute
  '/api/history': typeof ApiHistoryRoute
  '/api/me': typeof ApiMeRouteWithChildren
  '/api/messages': typeof ApiMessagesRoute
  '/api/notifications': typeof ApiNotificationsRoute
  '/api/otp/send': typeof ApiOtpSendRoute
  '/api/otp/verify': typeof ApiOtpVerifyRoute
  '/api/profile': typeof ApiProfileRoute
  '/api/reports': typeof ApiReportsRoute
  '/api/resolutions': typeof ApiResolutionsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/stats': typeof ApiStatsRoute
  '/api/trending': typeof ApiTrendingRoute
  '/api/upload': typeof ApiUploadRoute
  '/brand/login': typeof BrandLoginRoute
  '/brand/mesajlar': typeof BrandMesajlarRoute
  '/brand/profil': typeof BrandProfilRoute
  '/brand/sikayetler': typeof BrandSikayetlerRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/brand/': typeof BrandIndexRoute
  '/_site/(kurumsal)/erisim-yok': typeof SitekurumsalErisimYokRoute
  '/_site/(kurumsal)/gizlilik': typeof SitekurumsalGizlilikRoute
  '/_site/(kurumsal)/hakkimizda': typeof SitekurumsalHakkimizdaRoute
  '/_site/(kurumsal)/iletisim': typeof SitekurumsalIletisimRoute
  '/_site/(kurumsal)/kullanim-kosullari': typeof SitekurumsalKullanimKosullariRoute
  '/_site/(kurumsal)/kvkk': typeof SitekurumsalKvkkRoute
  '/_site/(kurumsal)/reklam-cozumleri': typeof SitekurumsalReklamCozumleriRoute
  '/_site/(kurumsal)/seffaflik-raporu': typeof SitekurumsalSeffaflikRaporuRoute
  '/_site/(kurumsal)/yardim': typeof SitekurumsalYardimRoute
  '/_site/blog/$slug': typeof SiteBlogSlugRoute
  '/_site/firma/$slug': typeof SiteFirmaSlugRoute
  '/_site/kategori/$slug': typeof SiteKategoriSlugRoute
  '/_site/sikayet/$id': typeof SiteSikayetIdRoute
  '/admin/firma/$id': typeof AdminFirmaIdRoute
  '/api/admin/blogs': typeof ApiAdminBlogsRoute
  '/api/admin/brands': typeof ApiAdminBrandsRouteWithChildren
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/cms': typeof ApiAdminCmsRoute
  '/api/admin/complaints': typeof ApiAdminComplaintsRoute
  '/api/admin/bot/config': typeof ApiAdminBotConfigRoute
  '/api/admin/bot/stats': typeof ApiAdminBotStatsRoute
  '/api/admin/bot/complaints': typeof ApiAdminBotComplaintsRoute
  '/api/admin/bot/generate': typeof ApiAdminBotGenerateRoute
  '/api/admin/bot/runs': typeof ApiAdminBotRunsRoute
  '/api/admin/escalations': typeof ApiAdminEscalationsRoute
  '/api/admin/media': typeof ApiAdminMediaRoute
  '/api/admin/moderation': typeof ApiAdminModerationRoute
  '/api/admin/premium': typeof ApiAdminPremiumRoute
  '/api/admin/sanctions': typeof ApiAdminSanctionsRoute
  '/api/admin/stats': typeof ApiAdminStatsRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/verification': typeof ApiAdminVerificationRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/brand/complaints': typeof ApiBrandComplaintsRoute
  '/api/brand/memberships': typeof ApiBrandMembershipsRoute
  '/api/brand/premium': typeof ApiBrandPremiumRoute
  '/api/brand/profile': typeof ApiBrandProfileRoute
  '/api/brand/stats': typeof ApiBrandStatsRoute
  '/api/brand/bot-config': typeof ApiBrandBotConfigRoute
  '/api/brands/$slug': typeof ApiBrandsSlugRoute
  '/api/comments/pin': typeof ApiCommentsPinRoute
  '/api/comments/vote': typeof ApiCommentsVoteRoute
  '/api/complaints/$id': typeof ApiComplaintsIdRoute
  '/api/events/$complaintId': typeof ApiEventsComplaintIdRoute
  '/api/files/$': typeof ApiFilesSplatRoute
  '/api/me/complaints': typeof ApiMeComplaintsRoute
  '/_site/blog/': typeof SiteBlogIndexRoute
  '/api/admin/brands/$id': typeof ApiAdminBrandsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brand'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/arama'
    | '/markalar'
    | '/profile'
    | '/sikayet-yaz'
    | '/sikayetler'
    | '/trend-100'
    | '/trendler'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/cms'
    | '/admin/dogrulama'
    | '/admin/escalations'
    | '/admin/firmalar'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/login'
    | '/admin/medya'
    | '/admin/moderasyon'
    | '/admin/premium'
    | '/admin/sikayetler'
    | '/admin/bot'
    | '/api/audit'
    | '/api/blog'
    | '/api/brand-ratings'
    | '/api/complaint-rating'
    | '/api/cron/complaint-bot'
    | '/api/brand-resolutions'
    | '/api/brand-verification'
    | '/api/brands'
    | '/api/categories'
    | '/api/comments'
    | '/api/complaint-replies'
    | '/api/complaints'
    | '/api/conversations'
    | '/api/escalations'
    | '/api/fastest-resolvers'
    | '/api/history'
    | '/api/me'
    | '/api/messages'
    | '/api/notifications'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile'
    | '/api/reports'
    | '/api/resolutions'
    | '/api/search'
    | '/api/stats'
    | '/api/trending'
    | '/api/upload'
    | '/brand/login'
    | '/brand/mesajlar'
    | '/brand/profil'
    | '/brand/sikayetler'
    | '/admin/'
    | '/brand/'
    | '/erisim-yok'
    | '/gizlilik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/reklam-cozumleri'
    | '/seffaflik-raporu'
    | '/yardim'
    | '/blog/$slug'
    | '/firma/$slug'
    | '/kategori/$slug'
    | '/sikayet/$id'
    | '/admin/firma/$id'
    | '/api/admin/blogs'
    | '/api/admin/brands'
    | '/api/admin/categories'
    | '/api/admin/cms'
    | '/api/admin/complaints'
    | '/api/admin/bot/config'
    | '/api/admin/bot/stats'
    | '/api/admin/bot/complaints'
    | '/api/admin/bot/generate'
    | '/api/admin/bot/runs'
    | '/api/admin/escalations'
    | '/api/admin/media'
    | '/api/admin/moderation'
    | '/api/admin/premium'
    | '/api/admin/sanctions'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/admin/verification'
    | '/api/auth/$'
    | '/api/brand/complaints'
    | '/api/brand/memberships'
    | '/api/brand/premium'
    | '/api/brand/profile'
    | '/api/brand/stats'
    | '/api/brand/bot-config'
    | '/api/brands/$slug'
    | '/api/comments/pin'
    | '/api/comments/vote'
    | '/api/complaints/$id'
    | '/api/events/$complaintId'
    | '/api/files/$'
    | '/api/me/complaints'
    | '/blog/'
    | '/api/admin/brands/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/verify-email'
    | '/arama'
    | '/markalar'
    | '/profile'
    | '/sikayet-yaz'
    | '/sikayetler'
    | '/trend-100'
    | '/trendler'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/cms'
    | '/admin/dogrulama'
    | '/admin/escalations'
    | '/admin/firmalar'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/login'
    | '/admin/medya'
    | '/admin/moderasyon'
    | '/admin/premium'
    | '/admin/sikayetler'
    | '/admin/bot'
    | '/api/audit'
    | '/api/blog'
    | '/api/brand-ratings'
    | '/api/complaint-rating'
    | '/api/cron/complaint-bot'
    | '/api/brand-resolutions'
    | '/api/brand-verification'
    | '/api/brands'
    | '/api/categories'
    | '/api/comments'
    | '/api/complaint-replies'
    | '/api/complaints'
    | '/api/conversations'
    | '/api/escalations'
    | '/api/fastest-resolvers'
    | '/api/history'
    | '/api/me'
    | '/api/messages'
    | '/api/notifications'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile'
    | '/api/reports'
    | '/api/resolutions'
    | '/api/search'
    | '/api/stats'
    | '/api/trending'
    | '/api/upload'
    | '/brand/login'
    | '/brand/mesajlar'
    | '/brand/profil'
    | '/brand/sikayetler'
    | '/'
    | '/admin'
    | '/brand'
    | '/erisim-yok'
    | '/gizlilik'
    | '/hakkimizda'
    | '/iletisim'
    | '/kullanim-kosullari'
    | '/kvkk'
    | '/reklam-cozumleri'
    | '/seffaflik-raporu'
    | '/yardim'
    | '/blog/$slug'
    | '/firma/$slug'
    | '/kategori/$slug'
    | '/sikayet/$id'
    | '/admin/firma/$id'
    | '/api/admin/blogs'
    | '/api/admin/brands'
    | '/api/admin/categories'
    | '/api/admin/cms'
    | '/api/admin/complaints'
    | '/api/admin/bot/config'
    | '/api/admin/bot/stats'
    | '/api/admin/bot/complaints'
    | '/api/admin/bot/generate'
    | '/api/admin/bot/runs'
    | '/api/admin/escalations'
    | '/api/admin/media'
    | '/api/admin/moderation'
    | '/api/admin/premium'
    | '/api/admin/sanctions'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/admin/verification'
    | '/api/auth/$'
    | '/api/brand/complaints'
    | '/api/brand/memberships'
    | '/api/brand/premium'
    | '/api/brand/profile'
    | '/api/brand/stats'
    | '/api/brand/bot-config'
    | '/api/brands/$slug'
    | '/api/comments/pin'
    | '/api/comments/vote'
    | '/api/complaints/$id'
    | '/api/events/$complaintId'
    | '/api/files/$'
    | '/api/me/complaints'
    | '/blog'
    | '/api/admin/brands/$id'
  id:
    | '__root__'
    | '/_site'
    | '/admin'
    | '/brand'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(auth)/reset-password'
    | '/(auth)/verify-email'
    | '/_site/arama'
    | '/_site/markalar'
    | '/_site/profile'
    | '/_site/sikayet-yaz'
    | '/_site/sikayetler'
    | '/_site/trend-100'
    | '/_site/trendler'
    | '/admin/ayarlar'
    | '/admin/blog'
    | '/admin/cms'
    | '/admin/dogrulama'
    | '/admin/escalations'
    | '/admin/firmalar'
    | '/admin/kategoriler'
    | '/admin/kullanicilar'
    | '/admin/login'
    | '/admin/medya'
    | '/admin/moderasyon'
    | '/admin/premium'
    | '/admin/sikayetler'
    | '/admin/bot'
    | '/api/audit'
    | '/api/blog'
    | '/api/brand-ratings'
    | '/api/complaint-rating'
    | '/api/cron/complaint-bot'
    | '/api/brand-resolutions'
    | '/api/brand-verification'
    | '/api/brands'
    | '/api/categories'
    | '/api/comments'
    | '/api/complaint-replies'
    | '/api/complaints'
    | '/api/conversations'
    | '/api/escalations'
    | '/api/fastest-resolvers'
    | '/api/history'
    | '/api/me'
    | '/api/messages'
    | '/api/notifications'
    | '/api/otp/send'
    | '/api/otp/verify'
    | '/api/profile'
    | '/api/reports'
    | '/api/resolutions'
    | '/api/search'
    | '/api/stats'
    | '/api/trending'
    | '/api/upload'
    | '/brand/login'
    | '/brand/mesajlar'
    | '/brand/profil'
    | '/brand/sikayetler'
    | '/_site/'
    | '/admin/'
    | '/brand/'
    | '/_site/(kurumsal)/erisim-yok'
    | '/_site/(kurumsal)/gizlilik'
    | '/_site/(kurumsal)/hakkimizda'
    | '/_site/(kurumsal)/iletisim'
    | '/_site/(kurumsal)/kullanim-kosullari'
    | '/_site/(kurumsal)/kvkk'
    | '/_site/(kurumsal)/reklam-cozumleri'
    | '/_site/(kurumsal)/seffaflik-raporu'
    | '/_site/(kurumsal)/yardim'
    | '/_site/blog/$slug'
    | '/_site/firma/$slug'
    | '/_site/kategori/$slug'
    | '/_site/sikayet/$id'
    | '/admin/firma/$id'
    | '/api/admin/blogs'
    | '/api/admin/brands'
    | '/api/admin/categories'
    | '/api/admin/cms'
    | '/api/admin/complaints'
    | '/api/admin/bot/config'
    | '/api/admin/bot/stats'
    | '/api/admin/bot/complaints'
    | '/api/admin/bot/generate'
    | '/api/admin/bot/runs'
    | '/api/admin/escalations'
    | '/api/admin/media'
    | '/api/admin/moderation'
    | '/api/admin/premium'
    | '/api/admin/sanctions'
    | '/api/admin/stats'
    | '/api/admin/users'
    | '/api/admin/verification'
    | '/api/auth/$'
    | '/api/brand/complaints'
    | '/api/brand/memberships'
    | '/api/brand/premium'
    | '/api/brand/profile'
    | '/api/brand/stats'
    | '/api/brand/bot-config'
    | '/api/brands/$slug'
    | '/api/comments/pin'
    | '/api/comments/vote'
    | '/api/complaints/$id'
    | '/api/events/$complaintId'
    | '/api/files/$'
    | '/api/me/complaints'
    | '/_site/blog/'
    | '/api/admin/brands/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  BrandRoute: typeof BrandRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiBlogRoute: typeof ApiBlogRoute
  ApiBrandRatingsRoute: typeof ApiBrandRatingsRoute
  ApiComplaintRatingRoute: typeof ApiComplaintRatingRoute
  ApiCronComplaintBotRoute: typeof ApiCronComplaintBotRoute
  ApiBrandResolutionsRoute: typeof ApiBrandResolutionsRoute
  ApiBrandVerificationRoute: typeof ApiBrandVerificationRoute
  ApiBrandsRoute: typeof ApiBrandsRouteWithChildren
  ApiCategoriesRoute: typeof ApiCategoriesRoute
  ApiCommentsRoute: typeof ApiCommentsRouteWithChildren
  ApiComplaintRepliesRoute: typeof ApiComplaintRepliesRoute
  ApiComplaintsRoute: typeof ApiComplaintsRouteWithChildren
  ApiConversationsRoute: typeof ApiConversationsRoute
  ApiEscalationsRoute: typeof ApiEscalationsRoute
  ApiFastestResolversRoute: typeof ApiFastestResolversRoute
  ApiHistoryRoute: typeof ApiHistoryRoute
  ApiMeRoute: typeof ApiMeRouteWithChildren
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiNotificationsRoute: typeof ApiNotificationsRoute
  ApiOtpSendRoute: typeof ApiOtpSendRoute
  ApiOtpVerifyRoute: typeof ApiOtpVerifyRoute
  ApiProfileRoute: typeof ApiProfileRoute
  ApiReportsRoute: typeof ApiReportsRoute
  ApiResolutionsRoute: typeof ApiResolutionsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiStatsRoute: typeof ApiStatsRoute
  ApiTrendingRoute: typeof ApiTrendingRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAdminBlogsRoute: typeof ApiAdminBlogsRoute
  ApiAdminBrandsRoute: typeof ApiAdminBrandsRouteWithChildren
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRoute
  ApiAdminCmsRoute: typeof ApiAdminCmsRoute
  ApiAdminComplaintsRoute: typeof ApiAdminComplaintsRoute
  ApiAdminBotConfigRoute: typeof ApiAdminBotConfigRoute
  ApiAdminBotStatsRoute: typeof ApiAdminBotStatsRoute
  ApiAdminBotComplaintsRoute: typeof ApiAdminBotComplaintsRoute
  ApiAdminBotGenerateRoute: typeof ApiAdminBotGenerateRoute
  ApiAdminBotRunsRoute: typeof ApiAdminBotRunsRoute
  ApiAdminEscalationsRoute: typeof ApiAdminEscalationsRoute
  ApiAdminMediaRoute: typeof ApiAdminMediaRoute
  ApiAdminModerationRoute: typeof ApiAdminModerationRoute
  ApiAdminPremiumRoute: typeof ApiAdminPremiumRoute
  ApiAdminSanctionsRoute: typeof ApiAdminSanctionsRoute
  ApiAdminStatsRoute: typeof ApiAdminStatsRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAdminVerificationRoute: typeof ApiAdminVerificationRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBrandComplaintsRoute: typeof ApiBrandComplaintsRoute
  ApiBrandMembershipsRoute: typeof ApiBrandMembershipsRoute
  ApiBrandPremiumRoute: typeof ApiBrandPremiumRoute
  ApiBrandProfileRoute: typeof ApiBrandProfileRoute
  ApiBrandStatsRoute: typeof ApiBrandStatsRoute
  ApiBrandBotConfigRoute: typeof ApiBrandBotConfigRoute
  ApiEventsComplaintIdRoute: typeof ApiEventsComplaintIdRoute
  ApiFilesSplatRoute: typeof ApiFilesSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/': {
      id: '/brand/'
      path: '/'
      fullPath: '/brand/'
      preLoaderRoute: typeof BrandIndexRouteImport
      parentRoute: typeof BrandRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/brand/sikayetler': {
      id: '/brand/sikayetler'
      path: '/sikayetler'
      fullPath: '/brand/sikayetler'
      preLoaderRoute: typeof BrandSikayetlerRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/profil': {
      id: '/brand/profil'
      path: '/profil'
      fullPath: '/brand/profil'
      preLoaderRoute: typeof BrandProfilRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/mesajlar': {
      id: '/brand/mesajlar'
      path: '/mesajlar'
      fullPath: '/brand/mesajlar'
      preLoaderRoute: typeof BrandMesajlarRouteImport
      parentRoute: typeof BrandRoute
    }
    '/brand/login': {
      id: '/brand/login'
      path: '/login'
      fullPath: '/brand/login'
      preLoaderRoute: typeof BrandLoginRouteImport
      parentRoute: typeof BrandRoute
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trending': {
      id: '/api/trending'
      path: '/api/trending'
      fullPath: '/api/trending'
      preLoaderRoute: typeof ApiTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stats': {
      id: '/api/stats'
      path: '/api/stats'
      fullPath: '/api/stats'
      preLoaderRoute: typeof ApiStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/resolutions': {
      id: '/api/resolutions'
      path: '/api/resolutions'
      fullPath: '/api/resolutions'
      preLoaderRoute: typeof ApiResolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reports': {
      id: '/api/reports'
      path: '/api/reports'
      fullPath: '/api/reports'
      preLoaderRoute: typeof ApiReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/profile': {
      id: '/api/profile'
      path: '/api/profile'
      fullPath: '/api/profile'
      preLoaderRoute: typeof ApiProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications': {
      id: '/api/notifications'
      path: '/api/notifications'
      fullPath: '/api/notifications'
      preLoaderRoute: typeof ApiNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp/send': {
      id: '/api/otp/send'
      path: '/api/otp/send'
      fullPath: '/api/otp/send'
      preLoaderRoute: typeof ApiOtpSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp/verify': {
      id: '/api/otp/verify'
      path: '/api/otp/verify'
      fullPath: '/api/otp/verify'
      preLoaderRoute: typeof ApiOtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/history': {
      id: '/api/history'
      path: '/api/history'
      fullPath: '/api/history'
      preLoaderRoute: typeof ApiHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fastest-resolvers': {
      id: '/api/fastest-resolvers'
      path: '/api/fastest-resolvers'
      fullPath: '/api/fastest-resolvers'
      preLoaderRoute: typeof ApiFastestResolversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/escalations': {
      id: '/api/escalations'
      path: '/api/escalations'
      fullPath: '/api/escalations'
      preLoaderRoute: typeof ApiEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations': {
      id: '/api/conversations'
      path: '/api/conversations'
      fullPath: '/api/conversations'
      preLoaderRoute: typeof ApiConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints': {
      id: '/api/complaints'
      path: '/api/complaints'
      fullPath: '/api/complaints'
      preLoaderRoute: typeof ApiComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaint-replies': {
      id: '/api/complaint-replies'
      path: '/api/complaint-replies'
      fullPath: '/api/complaint-replies'
      preLoaderRoute: typeof ApiComplaintRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/comments': {
      id: '/api/comments'
      path: '/api/comments'
      fullPath: '/api/comments'
      preLoaderRoute: typeof ApiCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/categories': {
      id: '/api/categories'
      path: '/api/categories'
      fullPath: '/api/categories'
      preLoaderRoute: typeof ApiCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brands': {
      id: '/api/brands'
      path: '/api/brands'
      fullPath: '/api/brands'
      preLoaderRoute: typeof ApiBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-verification': {
      id: '/api/brand-verification'
      path: '/api/brand-verification'
      fullPath: '/api/brand-verification'
      preLoaderRoute: typeof ApiBrandVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-resolutions': {
      id: '/api/brand-resolutions'
      path: '/api/brand-resolutions'
      fullPath: '/api/brand-resolutions'
      preLoaderRoute: typeof ApiBrandResolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand-ratings': {
      id: '/api/brand-ratings'
      path: '/api/brand-ratings'
      fullPath: '/api/brand-ratings'
      preLoaderRoute: typeof ApiBrandRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaint-rating': {
      id: '/api/complaint-rating'
      path: '/api/complaint-rating'
      fullPath: '/api/complaint-rating'
      preLoaderRoute: typeof ApiComplaintRatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/complaint-bot': {
      id: '/api/cron/complaint-bot'
      path: '/api/cron/complaint-bot'
      fullPath: '/api/cron/complaint-bot'
      preLoaderRoute: typeof ApiCronComplaintBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blog': {
      id: '/api/blog'
      path: '/api/blog'
      fullPath: '/api/blog'
      preLoaderRoute: typeof ApiBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sikayetler': {
      id: '/admin/sikayetler'
      path: '/sikayetler'
      fullPath: '/admin/sikayetler'
      preLoaderRoute: typeof AdminSikayetlerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bot': {
      id: '/admin/bot'
      path: '/bot'
      fullPath: '/admin/bot'
      preLoaderRoute: typeof AdminBotRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/premium': {
      id: '/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AdminPremiumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderasyon': {
      id: '/admin/moderasyon'
      path: '/moderasyon'
      fullPath: '/admin/moderasyon'
      preLoaderRoute: typeof AdminModerasyonRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/medya': {
      id: '/admin/medya'
      path: '/medya'
      fullPath: '/admin/medya'
      preLoaderRoute: typeof AdminMedyaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kullanicilar': {
      id: '/admin/kullanicilar'
      path: '/kullanicilar'
      fullPath: '/admin/kullanicilar'
      preLoaderRoute: typeof AdminKullanicilarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kategoriler': {
      id: '/admin/kategoriler'
      path: '/kategoriler'
      fullPath: '/admin/kategoriler'
      preLoaderRoute: typeof AdminKategorilerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/firmalar': {
      id: '/admin/firmalar'
      path: '/firmalar'
      fullPath: '/admin/firmalar'
      preLoaderRoute: typeof AdminFirmalarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escalations': {
      id: '/admin/escalations'
      path: '/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AdminEscalationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dogrulama': {
      id: '/admin/dogrulama'
      path: '/dogrulama'
      fullPath: '/admin/dogrulama'
      preLoaderRoute: typeof AdminDogrulamaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms': {
      id: '/admin/cms'
      path: '/cms'
      fullPath: '/admin/cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ayarlar': {
      id: '/admin/ayarlar'
      path: '/ayarlar'
      fullPath: '/admin/ayarlar'
      preLoaderRoute: typeof AdminAyarlarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/trendler': {
      id: '/_site/trendler'
      path: '/trendler'
      fullPath: '/trendler'
      preLoaderRoute: typeof SiteTrendlerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/trend-100': {
      id: '/_site/trend-100'
      path: '/trend-100'
      fullPath: '/trend-100'
      preLoaderRoute: typeof SiteTrend100RouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sikayetler': {
      id: '/_site/sikayetler'
      path: '/sikayetler'
      fullPath: '/sikayetler'
      preLoaderRoute: typeof SiteSikayetlerRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/sikayet-yaz': {
      id: '/_site/sikayet-yaz'
      path: '/sikayet-yaz'
      fullPath: '/sikayet-yaz'
      preLoaderRoute: typeof SiteSikayetYazRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/profile': {
      id: '/_site/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SiteProfileRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/markalar': {
      id: '/_site/markalar'
      path: '/markalar'
      fullPath: '/markalar'
      preLoaderRoute: typeof SiteMarkalarRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/arama': {
      id: '/_site/arama'
      path: '/arama'
      fullPath: '/arama'
      preLoaderRoute: typeof SiteAramaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/blog/': {
      id: '/_site/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof SiteBlogIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/me/complaints': {
      id: '/api/me/complaints'
      path: '/complaints'
      fullPath: '/api/me/complaints'
      preLoaderRoute: typeof ApiMeComplaintsRouteImport
      parentRoute: typeof ApiMeRoute
    }
    '/api/files/$': {
      id: '/api/files/$'
      path: '/api/files/$'
      fullPath: '/api/files/$'
      preLoaderRoute: typeof ApiFilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/$complaintId': {
      id: '/api/events/$complaintId'
      path: '/api/events/$complaintId'
      fullPath: '/api/events/$complaintId'
      preLoaderRoute: typeof ApiEventsComplaintIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/complaints/$id': {
      id: '/api/complaints/$id'
      path: '/$id'
      fullPath: '/api/complaints/$id'
      preLoaderRoute: typeof ApiComplaintsIdRouteImport
      parentRoute: typeof ApiComplaintsRoute
    }
    '/api/comments/vote': {
      id: '/api/comments/vote'
      path: '/vote'
      fullPath: '/api/comments/vote'
      preLoaderRoute: typeof ApiCommentsVoteRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/comments/pin': {
      id: '/api/comments/pin'
      path: '/pin'
      fullPath: '/api/comments/pin'
      preLoaderRoute: typeof ApiCommentsPinRouteImport
      parentRoute: typeof ApiCommentsRoute
    }
    '/api/brands/$slug': {
      id: '/api/brands/$slug'
      path: '/$slug'
      fullPath: '/api/brands/$slug'
      preLoaderRoute: typeof ApiBrandsSlugRouteImport
      parentRoute: typeof ApiBrandsRoute
    }
    '/api/brand/stats': {
      id: '/api/brand/stats'
      path: '/api/brand/stats'
      fullPath: '/api/brand/stats'
      preLoaderRoute: typeof ApiBrandStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/bot-config': {
      id: '/api/brand/bot-config'
      path: '/api/brand/bot-config'
      fullPath: '/api/brand/bot-config'
      preLoaderRoute: typeof ApiBrandBotConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/profile': {
      id: '/api/brand/profile'
      path: '/api/brand/profile'
      fullPath: '/api/brand/profile'
      preLoaderRoute: typeof ApiBrandProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/premium': {
      id: '/api/brand/premium'
      path: '/api/brand/premium'
      fullPath: '/api/brand/premium'
      preLoaderRoute: typeof ApiBrandPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/memberships': {
      id: '/api/brand/memberships'
      path: '/api/brand/memberships'
      fullPath: '/api/brand/memberships'
      preLoaderRoute: typeof ApiBrandMembershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/brand/complaints': {
      id: '/api/brand/complaints'
      path: '/api/brand/complaints'
      fullPath: '/api/brand/complaints'
      preLoaderRoute: typeof ApiBrandComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/verification': {
      id: '/api/admin/verification'
      path: '/api/admin/verification'
      fullPath: '/api/admin/verification'
      preLoaderRoute: typeof ApiAdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/stats': {
      id: '/api/admin/stats'
      path: '/api/admin/stats'
      fullPath: '/api/admin/stats'
      preLoaderRoute: typeof ApiAdminStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sanctions': {
      id: '/api/admin/sanctions'
      path: '/api/admin/sanctions'
      fullPath: '/api/admin/sanctions'
      preLoaderRoute: typeof ApiAdminSanctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/premium': {
      id: '/api/admin/premium'
      path: '/api/admin/premium'
      fullPath: '/api/admin/premium'
      preLoaderRoute: typeof ApiAdminPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/moderation': {
      id: '/api/admin/moderation'
      path: '/api/admin/moderation'
      fullPath: '/api/admin/moderation'
      preLoaderRoute: typeof ApiAdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media': {
      id: '/api/admin/media'
      path: '/api/admin/media'
      fullPath: '/api/admin/media'
      preLoaderRoute: typeof ApiAdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/escalations': {
      id: '/api/admin/escalations'
      path: '/api/admin/escalations'
      fullPath: '/api/admin/escalations'
      preLoaderRoute: typeof ApiAdminEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/complaints': {
      id: '/api/admin/complaints'
      path: '/api/admin/complaints'
      fullPath: '/api/admin/complaints'
      preLoaderRoute: typeof ApiAdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot/config': {
      id: '/api/admin/bot/config'
      path: '/api/admin/bot/config'
      fullPath: '/api/admin/bot/config'
      preLoaderRoute: typeof ApiAdminBotConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot/stats': {
      id: '/api/admin/bot/stats'
      path: '/api/admin/bot/stats'
      fullPath: '/api/admin/bot/stats'
      preLoaderRoute: typeof ApiAdminBotStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot/complaints': {
      id: '/api/admin/bot/complaints'
      path: '/api/admin/bot/complaints'
      fullPath: '/api/admin/bot/complaints'
      preLoaderRoute: typeof ApiAdminBotComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot/generate': {
      id: '/api/admin/bot/generate'
      path: '/api/admin/bot/generate'
      fullPath: '/api/admin/bot/generate'
      preLoaderRoute: typeof ApiAdminBotGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/bot/runs': {
      id: '/api/admin/bot/runs'
      path: '/api/admin/bot/runs'
      fullPath: '/api/admin/bot/runs'
      preLoaderRoute: typeof ApiAdminBotRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/cms': {
      id: '/api/admin/cms'
      path: '/api/admin/cms'
      fullPath: '/api/admin/cms'
      preLoaderRoute: typeof ApiAdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/brands': {
      id: '/api/admin/brands'
      path: '/api/admin/brands'
      fullPath: '/api/admin/brands'
      preLoaderRoute: typeof ApiAdminBrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/blogs': {
      id: '/api/admin/blogs'
      path: '/api/admin/blogs'
      fullPath: '/api/admin/blogs'
      preLoaderRoute: typeof ApiAdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/firma/$id': {
      id: '/admin/firma/$id'
      path: '/firma/$id'
      fullPath: '/admin/firma/$id'
      preLoaderRoute: typeof AdminFirmaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_site/sikayet/$id': {
      id: '/_site/sikayet/$id'
      path: '/sikayet/$id'
      fullPath: '/sikayet/$id'
      preLoaderRoute: typeof SiteSikayetIdRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kategori/$slug': {
      id: '/_site/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof SiteKategoriSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/firma/$slug': {
      id: '/_site/firma/$slug'
      path: '/firma/$slug'
      fullPath: '/firma/$slug'
      preLoaderRoute: typeof SiteFirmaSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog/$slug': {
      id: '/_site/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof SiteBlogSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/yardim': {
      id: '/_site/(kurumsal)/yardim'
      path: '/yardim'
      fullPath: '/yardim'
      preLoaderRoute: typeof SitekurumsalYardimRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/seffaflik-raporu': {
      id: '/_site/(kurumsal)/seffaflik-raporu'
      path: '/seffaflik-raporu'
      fullPath: '/seffaflik-raporu'
      preLoaderRoute: typeof SitekurumsalSeffaflikRaporuRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/reklam-cozumleri': {
      id: '/_site/(kurumsal)/reklam-cozumleri'
      path: '/reklam-cozumleri'
      fullPath: '/reklam-cozumleri'
      preLoaderRoute: typeof SitekurumsalReklamCozumleriRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/kvkk': {
      id: '/_site/(kurumsal)/kvkk'
      path: '/kvkk'
      fullPath: '/kvkk'
      preLoaderRoute: typeof SitekurumsalKvkkRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/kullanim-kosullari': {
      id: '/_site/(kurumsal)/kullanim-kosullari'
      path: '/kullanim-kosullari'
      fullPath: '/kullanim-kosullari'
      preLoaderRoute: typeof SitekurumsalKullanimKosullariRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/iletisim': {
      id: '/_site/(kurumsal)/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof SitekurumsalIletisimRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/hakkimizda': {
      id: '/_site/(kurumsal)/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof SitekurumsalHakkimizdaRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/gizlilik': {
      id: '/_site/(kurumsal)/gizlilik'
      path: '/gizlilik'
      fullPath: '/gizlilik'
      preLoaderRoute: typeof SitekurumsalGizlilikRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/(kurumsal)/erisim-yok': {
      id: '/_site/(kurumsal)/erisim-yok'
      path: '/erisim-yok'
      fullPath: '/erisim-yok'
      preLoaderRoute: typeof SitekurumsalErisimYokRouteImport
      parentRoute: typeof SiteRoute
    }
    '/api/admin/brands/$id': {
      id: '/api/admin/brands/$id'
      path: '/$id'
      fullPath: '/api/admin/brands/$id'
      preLoaderRoute: typeof ApiAdminBrandsIdRouteImport
      parentRoute: typeof ApiAdminBrandsRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAramaRoute: typeof SiteAramaRoute
  SiteMarkalarRoute: typeof SiteMarkalarRoute
  SiteProfileRoute: typeof SiteProfileRoute
  SiteSikayetYazRoute: typeof SiteSikayetYazRoute
  SiteSikayetlerRoute: typeof SiteSikayetlerRoute
  SiteTrend100Route: typeof SiteTrend100Route
  SiteTrendlerRoute: typeof SiteTrendlerRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitekurumsalErisimYokRoute: typeof SitekurumsalErisimYokRoute
  SitekurumsalGizlilikRoute: typeof SitekurumsalGizlilikRoute
  SitekurumsalHakkimizdaRoute: typeof SitekurumsalHakkimizdaRoute
  SitekurumsalIletisimRoute: typeof SitekurumsalIletisimRoute
  SitekurumsalKullanimKosullariRoute: typeof SitekurumsalKullanimKosullariRoute
  SitekurumsalKvkkRoute: typeof SitekurumsalKvkkRoute
  SitekurumsalReklamCozumleriRoute: typeof SitekurumsalReklamCozumleriRoute
  SitekurumsalSeffaflikRaporuRoute: typeof SitekurumsalSeffaflikRaporuRoute
  SitekurumsalYardimRoute: typeof SitekurumsalYardimRoute
  SiteBlogSlugRoute: typeof SiteBlogSlugRoute
  SiteFirmaSlugRoute: typeof SiteFirmaSlugRoute
  SiteKategoriSlugRoute: typeof SiteKategoriSlugRoute
  SiteSikayetIdRoute: typeof SiteSikayetIdRoute
  SiteBlogIndexRoute: typeof SiteBlogIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAramaRoute: SiteAramaRoute,
  SiteMarkalarRoute: SiteMarkalarRoute,
  SiteProfileRoute: SiteProfileRoute,
  SiteSikayetYazRoute: SiteSikayetYazRoute,
  SiteSikayetlerRoute: SiteSikayetlerRoute,
  SiteTrend100Route: SiteTrend100Route,
  SiteTrendlerRoute: SiteTrendlerRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitekurumsalErisimYokRoute: SitekurumsalErisimYokRoute,
  SitekurumsalGizlilikRoute: SitekurumsalGizlilikRoute,
  SitekurumsalHakkimizdaRoute: SitekurumsalHakkimizdaRoute,
  SitekurumsalIletisimRoute: SitekurumsalIletisimRoute,
  SitekurumsalKullanimKosullariRoute: SitekurumsalKullanimKosullariRoute,
  SitekurumsalKvkkRoute: SitekurumsalKvkkRoute,
  SitekurumsalReklamCozumleriRoute: SitekurumsalReklamCozumleriRoute,
  SitekurumsalSeffaflikRaporuRoute: SitekurumsalSeffaflikRaporuRoute,
  SitekurumsalYardimRoute: SitekurumsalYardimRoute,
  SiteBlogSlugRoute: SiteBlogSlugRoute,
  SiteFirmaSlugRoute: SiteFirmaSlugRoute,
  SiteKategoriSlugRoute: SiteKategoriSlugRoute,
  SiteSikayetIdRoute: SiteSikayetIdRoute,
  SiteBlogIndexRoute: SiteBlogIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AdminRouteChildren {
  AdminAyarlarRoute: typeof AdminAyarlarRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminDogrulamaRoute: typeof AdminDogrulamaRoute
  AdminEscalationsRoute: typeof AdminEscalationsRoute
  AdminFirmalarRoute: typeof AdminFirmalarRoute
  AdminKategorilerRoute: typeof AdminKategorilerRoute
  AdminKullanicilarRoute: typeof AdminKullanicilarRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMedyaRoute: typeof AdminMedyaRoute
  AdminModerasyonRoute: typeof AdminModerasyonRoute
  AdminPremiumRoute: typeof AdminPremiumRoute
  AdminSikayetlerRoute: typeof AdminSikayetlerRoute
  AdminBotRoute: typeof AdminBotRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminFirmaIdRoute: typeof AdminFirmaIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAyarlarRoute: AdminAyarlarRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminDogrulamaRoute: AdminDogrulamaRoute,
  AdminEscalationsRoute: AdminEscalationsRoute,
  AdminFirmalarRoute: AdminFirmalarRoute,
  AdminKategorilerRoute: AdminKategorilerRoute,
  AdminKullanicilarRoute: AdminKullanicilarRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMedyaRoute: AdminMedyaRoute,
  AdminModerasyonRoute: AdminModerasyonRoute,
  AdminPremiumRoute: AdminPremiumRoute,
  AdminSikayetlerRoute: AdminSikayetlerRoute,
  AdminBotRoute: AdminBotRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminFirmaIdRoute: AdminFirmaIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BrandRouteChildren {
  BrandLoginRoute: typeof BrandLoginRoute
  BrandMesajlarRoute: typeof BrandMesajlarRoute
  BrandProfilRoute: typeof BrandProfilRoute
  BrandSikayetlerRoute: typeof BrandSikayetlerRoute
  BrandIndexRoute: typeof BrandIndexRoute
}

const BrandRouteChildren: BrandRouteChildren = {
  BrandLoginRoute: BrandLoginRoute,
  BrandMesajlarRoute: BrandMesajlarRoute,
  BrandProfilRoute: BrandProfilRoute,
  BrandSikayetlerRoute: BrandSikayetlerRoute,
  BrandIndexRoute: BrandIndexRoute,
}

const BrandRouteWithChildren = BrandRoute._addFileChildren(BrandRouteChildren)

interface ApiBrandsRouteChildren {
  ApiBrandsSlugRoute: typeof ApiBrandsSlugRoute
}

const ApiBrandsRouteChildren: ApiBrandsRouteChildren = {
  ApiBrandsSlugRoute: ApiBrandsSlugRoute,
}

const ApiBrandsRouteWithChildren = ApiBrandsRoute._addFileChildren(
  ApiBrandsRouteChildren,
)

interface ApiCommentsRouteChildren {
  ApiCommentsPinRoute: typeof ApiCommentsPinRoute
  ApiCommentsVoteRoute: typeof ApiCommentsVoteRoute
}

const ApiCommentsRouteChildren: ApiCommentsRouteChildren = {
  ApiCommentsPinRoute: ApiCommentsPinRoute,
  ApiCommentsVoteRoute: ApiCommentsVoteRoute,
}

const ApiCommentsRouteWithChildren = ApiCommentsRoute._addFileChildren(
  ApiCommentsRouteChildren,
)

interface ApiComplaintsRouteChildren {
  ApiComplaintsIdRoute: typeof ApiComplaintsIdRoute
}

const ApiComplaintsRouteChildren: ApiComplaintsRouteChildren = {
  ApiComplaintsIdRoute: ApiComplaintsIdRoute,
}

const ApiComplaintsRouteWithChildren = ApiComplaintsRoute._addFileChildren(
  ApiComplaintsRouteChildren,
)

interface ApiMeRouteChildren {
  ApiMeComplaintsRoute: typeof ApiMeComplaintsRoute
}

const ApiMeRouteChildren: ApiMeRouteChildren = {
  ApiMeComplaintsRoute: ApiMeComplaintsRoute,
}

const ApiMeRouteWithChildren = ApiMeRoute._addFileChildren(ApiMeRouteChildren)

interface ApiAdminBrandsRouteChildren {
  ApiAdminBrandsIdRoute: typeof ApiAdminBrandsIdRoute
}

const ApiAdminBrandsRouteChildren: ApiAdminBrandsRouteChildren = {
  ApiAdminBrandsIdRoute: ApiAdminBrandsIdRoute,
}

const ApiAdminBrandsRouteWithChildren = ApiAdminBrandsRoute._addFileChildren(
  ApiAdminBrandsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  BrandRoute: BrandRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiBlogRoute: ApiBlogRoute,
  ApiBrandRatingsRoute: ApiBrandRatingsRoute,
  ApiComplaintRatingRoute: ApiComplaintRatingRoute,
  ApiCronComplaintBotRoute: ApiCronComplaintBotRoute,
  ApiBrandResolutionsRoute: ApiBrandResolutionsRoute,
  ApiBrandVerificationRoute: ApiBrandVerificationRoute,
  ApiBrandsRoute: ApiBrandsRouteWithChildren,
  ApiCategoriesRoute: ApiCategoriesRoute,
  ApiCommentsRoute: ApiCommentsRouteWithChildren,
  ApiComplaintRepliesRoute: ApiComplaintRepliesRoute,
  ApiComplaintsRoute: ApiComplaintsRouteWithChildren,
  ApiConversationsRoute: ApiConversationsRoute,
  ApiEscalationsRoute: ApiEscalationsRoute,
  ApiFastestResolversRoute: ApiFastestResolversRoute,
  ApiHistoryRoute: ApiHistoryRoute,
  ApiMeRoute: ApiMeRouteWithChildren,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiNotificationsRoute: ApiNotificationsRoute,
  ApiOtpSendRoute: ApiOtpSendRoute,
  ApiOtpVerifyRoute: ApiOtpVerifyRoute,
  ApiProfileRoute: ApiProfileRoute,
  ApiReportsRoute: ApiReportsRoute,
  ApiResolutionsRoute: ApiResolutionsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiStatsRoute: ApiStatsRoute,
  ApiTrendingRoute: ApiTrendingRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAdminBlogsRoute: ApiAdminBlogsRoute,
  ApiAdminBrandsRoute: ApiAdminBrandsRouteWithChildren,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRoute,
  ApiAdminCmsRoute: ApiAdminCmsRoute,
  ApiAdminComplaintsRoute: ApiAdminComplaintsRoute,
  ApiAdminBotConfigRoute: ApiAdminBotConfigRoute,
  ApiAdminBotStatsRoute: ApiAdminBotStatsRoute,
  ApiAdminBotComplaintsRoute: ApiAdminBotComplaintsRoute,
  ApiAdminBotGenerateRoute: ApiAdminBotGenerateRoute,
  ApiAdminBotRunsRoute: ApiAdminBotRunsRoute,
  ApiAdminEscalationsRoute: ApiAdminEscalationsRoute,
  ApiAdminMediaRoute: ApiAdminMediaRoute,
  ApiAdminModerationRoute: ApiAdminModerationRoute,
  ApiAdminPremiumRoute: ApiAdminPremiumRoute,
  ApiAdminSanctionsRoute: ApiAdminSanctionsRoute,
  ApiAdminStatsRoute: ApiAdminStatsRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAdminVerificationRoute: ApiAdminVerificationRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBrandComplaintsRoute: ApiBrandComplaintsRoute,
  ApiBrandMembershipsRoute: ApiBrandMembershipsRoute,
  ApiBrandPremiumRoute: ApiBrandPremiumRoute,
  ApiBrandProfileRoute: ApiBrandProfileRoute,
  ApiBrandStatsRoute: ApiBrandStatsRoute,
  ApiBrandBotConfigRoute: ApiBrandBotConfigRoute,
  ApiEventsComplaintIdRoute: ApiEventsComplaintIdRoute,
  ApiFilesSplatRoute: ApiFilesSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
